services:
  server:
    container_name: sn-server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    restart: on-failure
    volumes:
      - ./server:/usr/share/app
      - /usr/share/app/node_modules

  db:
    container_name: sn-db
    image: postgres:16.3-alpine3.20
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    container_name: sn-db-ui
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    container_name: sn-redis
    image: redis:7.2.5-alpine
    restart: on-failure
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

  redis-commander:
    container_name: sn-redis-ui
    image: ghcr.io/joeferner/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=${REDIS_HOST}:redis:${REDIS_PORT}
    ports:
      - 8081:8081

volumes:
  db_data:
  redis_data:
