version: '3.9'

services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: db-ui
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  redis:
    image: redis:7.2.5-alpine
    container_name: redis
    ports:
      - 6379:6379

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-ui
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=${REDIS_HOST}:redis:${REDIS_PORT}
    ports:
      - 8081:8081

volumes:
  db_data:
